name: Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build_and_push:
    name: Build & Publish Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          # https://github.com/AlexanderYastrebov/wireguard-vanity-key/commit/9397d4544ba6daf55ff866dc4fe4d510f54fbda8
          tags: |
            ghcr.io/${{ github.repository_owner == 'AlexanderYastrebov' && 'alexanderyastrebov' || github.repository_owner }}/wireguard-vanity-key:latest
